version: '3'
services:
  app:
    depends_on: 
      - postgres
    image: cosmtrek/air
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: bash -c "
        apt-get update
        && apt-get install -y postgresql-client
        && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
        && migrate -database "postgres://postgres:password@postgres:5432/multiplayer?sslmode=disable" -path=db/migrations up
        && /go/bin/air
      "
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=multiplayer
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
