// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: add_document_contributor.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDocumentContributor = `-- name: CreateDocumentContributor :exec
INSERT INTO document_contributors (document_id, user_id)
VALUES ($1, $2)
`

type CreateDocumentContributorParams struct {
	DocumentID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) CreateDocumentContributor(ctx context.Context, arg CreateDocumentContributorParams) error {
	_, err := q.db.Exec(ctx, createDocumentContributor, arg.DocumentID, arg.UserID)
	return err
}
