// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: add_document_contributor.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addDocumentContributor = `-- name: AddDocumentContributor :exec
UPDATE documents 
SET shared_with = $2
WHERE id = $1
`

type AddDocumentContributorParams struct {
	ID         uuid.UUID
	SharedWith []uuid.UUID
}

func (q *Queries) AddDocumentContributor(ctx context.Context, arg AddDocumentContributorParams) error {
	_, err := q.db.Exec(ctx, addDocumentContributor, arg.ID, arg.SharedWith)
	return err
}
