// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: create_document_update.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUpdate = `-- name: CreateUpdate :one
SELECT COALESCE(MAX(clock), 0) AS current_clock
FROM document_updates
WHERE document_id = $1
`

func (q *Queries) CreateUpdate(ctx context.Context, documentID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, createUpdate, documentID)
	var current_clock interface{}
	err := row.Scan(&current_clock)
	return current_clock, err
}
