// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: create_document.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (name, owner_id)
    VALUES ($1, $2)
RETURNING id, name, owner_id, shared_with, content
`

type CreateDocumentParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.Name, arg.OwnerID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.SharedWith,
		&i.Content,
	)
	return i, err
}
