// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: create_document.sql

package db

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (name)
    VALUES ($1)
RETURNING id, name, owner_id, content
`

func (q *Queries) CreateDocument(ctx context.Context, name string) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, name)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Content,
	)
	return i, err
}
