// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: create_user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, passhash)
    VALUES ($1, $2)
RETURNING id, email, passhash
`

type CreateUserParams struct {
	Email    string
	Passhash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Passhash)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Passhash)
	return i, err
}
