// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: get_documents_by_owner_id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentsByOwnerID = `-- name: GetDocumentsByOwnerID :many
SELECT id, name, owner_id, shared_with, content FROM documents WHERE owner_id = $1
`

func (q *Queries) GetDocumentsByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.SharedWith,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
