// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: get_document_by_id.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, name, owner_id, state_vector FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.StateVector,
	)
	return i, err
}
