// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/google/uuid"
)

type Document struct {
	ID         uuid.UUID
	Name       string
	OwnerID    uuid.UUID
	SharedWith []uuid.UUID
	Content    []byte
}

type User struct {
	ID       uuid.UUID
	Email    string
	Username string
	Passhash string
}
