name: Push

on: [ push, pull_request ]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Test
      run: go test -v ./tests/...

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t rejdeboer.azurecr.io/repo:multiplayer-server-${{ github.run_number }} .

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets. ARM_SUBSCRIPTION_ID }}

      - name: Push image to ACR
        run: docker push rejdeboer.azurecr.io/repo:multiplayer-server-${{ github.run_number }}

  modify-manifest:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out config repo
        uses: actions/checkout@v3
        with:
          repository: 'rejdeboer/multiplayer-server-deployment'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify application image
        run: |
          git config user.email rick.deboer@live.nl
          git config user.name rejdeboer
          sed -i "s+rejdeboer.azurecr.io/repo:multiplayer-server.*+rejdeboer.azurecr.io/repo:multiplayer-server-$RUN_NUMBER+g" kubernetes/multiplayer-server-deployment.yml
          git add .
          git commit -m 'automated: update application image'
          git push https://rejdeboer:${GH_TOKEN}@github.com/rejdeboer/multiplayer-deployment.git master
        env:
          RUN_NUMBER: ${{ github.run_number }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
