name: Push

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Test
      run: go test -v ./tests/...

    - name: Build container image
      run: docker build -t emailapi.azurecr.io/repo:email-api .

    - name: Azure login
      run: az login

    - name: Push image to ACR
      run: docker push emailapi.azurecr.io/repo:email-api
